apiVersion: v1
kind: Pod
metadata:
  name: gpu-shared
spec:
  containers:
  - args:
    - sleep infinity
    command:
    - /bin/bash
    - -c
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    name: gpu-shared
    resources:
      limits:
        nvidia.com/gpu: "2"
        nvidia.com/gpucores: "70"
        nvidia.com/gpumem: "1024"
