apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-binpack
spec:
  replicas: 5
  selector:
    matchLabels:
      app-name: gpu-binpack
  template:
    metadata:
      annotations:
        hami.io/gpu-scheduler-policy: binpack
      labels:
        app-name: gpu-binpack
    spec:
      containers:
      - args:
        - sleep infinity
        command:
        - /bin/bash
        - -c
        image: ubuntu:latest
        name: main
        resources:
          limits:
            nvidia.com/gpu: "1"
            nvidia.com/gpucores: "10"
            nvidia.com/gpumem: "1024"
