apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-binpack
spec:
  replicas: 5
  selector:
    matchLabels:
      app-name: gpu-binpack
  template:
    metadata:
      annotations:
        hami.io/gpu-scheduler-policy: binpack
      labels:
        app-name: gpu-binpack
    spec:
      containers:
      - args:
        - while :; do /app/gpu_burn 300 || true; sleep 300; done
        command:
        - /bin/sh
        - -lc
        image: oguzpastirmaci/gpu-burn:latest
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          limits:
            nvidia.com/gpu: "1"
            nvidia.com/gpucores: "10"
            nvidia.com/gpumem: "1024"
          requests:
            nvidia.com/gpu: "1"
            nvidia.com/gpucores: "10"
            nvidia.com/gpumem: "1024"