apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: vllm
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 2
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          role: leader
      spec:
        containers:
          - name: vllm-leader
            image: vllm/vllm-openai:latest
            imagePullPolicy: IfNotPresent
            command:
              - sh
              - -c
              - "bash /vllm-workspace/examples/online_serving/multi-node-serving.sh leader --ray_cluster_size=$(LWS_GROUP_SIZE); 
                 python3 -m vllm.entrypoints.openai.api_server --port 8080 --model Qwen/Qwen3-4B --tensor-parallel-size 2 --enforce-eagle --max-model-len=1024 --dtype=auto"
            resources:
              limits:
                cpu: "1"
                memory: 6Gi
                nvidia.com/gpu: "1"
                nvidia.com/gpucores: "50"
                nvidia.com/gpumem: "10240"
                nvidia.com/priority: "1"
              requests:
                cpu: "1"
                memory: 6Gi
                nvidia.com/gpu: "1"
                nvidia.com/gpucores: "50"
                nvidia.com/gpumem: "10240"
                nvidia.com/priority: "1"
            ports:
              - containerPort: 8080
            readinessProbe:
              tcpSocket:
                port: 8080
              initialDelaySeconds: 15
              periodSeconds: 10
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 15Gi
    workerTemplate:
      spec:
        containers:
          - name: vllm-worker
            image: vllm/vllm-openai:latest
            imagePullPolicy: IfNotPresent
            command:
              - sh
              - -c
              - "bash /vllm-workspace/examples/online_serving/multi-node-serving.sh worker --ray_address=$(LWS_LEADER_ADDRESS)"
            resources:
              limits:
                cpu: "1"
                memory: 6Gi
                nvidia.com/gpu: "1"
                nvidia.com/gpucores: "50"
                nvidia.com/gpumem: "10240"
                nvidia.com/priority: "1"
              requests:
                cpu: "1"
                memory: 6Gi
                nvidia.com/gpu: "1"
                nvidia.com/gpucores: "50"
                nvidia.com/gpumem: "10240"
                nvidia.com/priority: "1"
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm   
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 15Gi
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-leader
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    leaderworkerset.sigs.k8s.io/name: vllm
    role: leader
  type: ClusterIP