apiVersion: v1
kind: Pod
metadata:
  name: auto-memory-scaling
spec:
  containers:
  - args:
    - sleep infinity
    env:
    - name: CUDA_MEMORY_AUTO_ADJUST
      value: "true"
    command:
    - /bin/bash
    - -c
    image: pytorch/pytorch:2.7.1-cuda12.6-cudnn9-devel
    imagePullPolicy: IfNotPresent
    name: auto-memory-scaling
    resources:
      limits:
        nvidia.com/gpu: "1"
        nvidia.com/gpucores: "50"
        nvidia.com/gpumem: "200"
