apiVersion: v1
kind: Pod
metadata:
  name: memory-scaling
spec:
  containers:
  - args:
    - sleep infinity
    command:
    - /bin/bash
    - -c
    image: pytorch/pytorch:2.7.1-cuda12.6-cudnn9-devel
    imagePullPolicy: IfNotPresent
    name: memory-scaling
    resources:
      limits:
        nvidia.com/gpu: "1"
        nvidia.com/gpucores: "50"
        nvidia.com/gpumem: "256"
