apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-spread
spec:
  replicas: 5
  selector:
    matchLabels:
      app-name: node-spread
  template:
    metadata:
      annotations:
        hami.io/node-scheduler-policy: spread
      labels:
        app-name: node-spread
    spec:
      containers:
      - args:
        - sleep infinity
        command:
        - /bin/bash
        - -c
        image: ubuntu:latest
        name: main
        resources:
          limits:
            nvidia.com/gpu: "1"
            nvidia.com/gpucores: "10"
            nvidia.com/gpumem: "1024"
