apiVersion: v1
kind: Pod
metadata:
  annotations:
  name: priority
spec:
  containers:
  - args:
    - sleep infinity
    command:
    - /bin/bash
    - -c
    env:
      - name: CUDA_TASK_PRIORITY
        value: '0'
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    name: high-priority
    resources:
      limits:
        nvidia.com/gpu: "1"
        nvidia.com/gpucores: "10"
        nvidia.com/gpumem: "1024"
  - args:
    - sleep infinity
    command:
    - /bin/bash
    - -c
    env:
      - name: CUDA_TASK_PRIORITY
        value: '1'
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    name: low-priority
    resources:
      limits:
        nvidia.com/gpu: "1"
        nvidia.com/gpucores: "10"
        nvidia.com/gpumem: "1024"
